### ISSUE TITLE
Login stopped working

### ISSUE THREAD

**Issue by texnixe** [Woeler/komoot-php#1]
Firstly, thanks for providing this useful script. It worked great until very recently. Guess Komoot made some changes to their endpoints since, so that the login now doesn't work anymore. Would be great if that issue could be fixed, will also try to look into it myself if I find the time.

The error message I'm getting is 

```
Client error: `POST https://account.komoot.com/v1/signin` resulted in a `400 Bad Request` response: {"type":"login","error":"unknown","email":"hello@example.com","code":400} 
```

**Comment by Woeler** [comment]
Unfortunately komoot added an invisible captcha to their login process, which breaks the library. I have sent them an email, but no response yet. I don't have high hopes they will give us a solution unfortunately.

**Comment by Woeler** [comment]
Here's Komoot's answer to me asking about it. I guess they don't like people doing these kinds of things. Shame. 
> Hi Woeler,
>  
> Thank you for your message and please accept our apologies for the delay in getting back to you. We have experienced a significant increase in support queries recently. We’re glad to hear you’ve found a unique way to manage and customize your activities!
>  
> Generally, we don’t officially support custom-built login tools. Could you let us know if logging in through the official komoot app or a standard web browser works as expected? 
>  
> Thanks again, and feel free to get in touch if you have more questions.
>  
> Have a great weekend!
>  
> Best,

**Comment by texnixe** [comment]
Hi @Woeler. Thanks for the update. Yes, already considered that as well, but at least OutdoorActive don't have an official API that is open to the public, or is really expensive, not intended for private use. Unless there is a way to hack yourself in as well until that shut that down.

Interestingly, it is still possible to download data via some Python or JavaScript tools that use the v6 endpoints.

Please keep me up to date if you find a new app. I really like Komoot for tour planning, but prefer to have my tracked data accessible in my own tools for statistics.

**Comment by Woeler** [comment]
@texnixe Do you have links to these python tools? Can they carry out logins?

**Comment by texnixe** [comment]
I played around with these two tools:
- https://pypi.org/project/komootgpx/ (Python)
- https://github.com/DasRed/komoot2csv (JS)

**Comment by Woeler** [comment]
@texnixe I'm pleased to announce that I have found a fix! I will be releasing v2 of the lib tonight! It has some breaking changes tho, but it works again. Hooray!

**Comment by texnixe** [comment]
Great, thanks!
